# Generated by Django 6.0.4 on 2026-06-24 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_sabores', '0002_usuariopermitido'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsuarioPermitido',
        ),
    ]
