# Generated by Django 6.0.4 on 2026-06-23 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioPermitido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('codigo_validacion', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Usuario Permitido',
                'verbose_name_plural': 'Usuarios Permitidos',
            },
        ),
    ]
